restaurant/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/',
         views.cart_add,
         name='cart_add'),
    path('remove/<int:product_id>/',
         views.cart_remove,
         name='cart_remove'),
]

restaurant/indianexpress/urls.py
from django.conf.urls import url
from . import views
from django.urls import path, re_path

app_name = 'indianexpress'
urlpatterns = [
    path('', views.home, name='home'),
    re_path(r'^home/$', views.home, name='home'),
    path('signup/', views.signup, name="signup"),
    path('reservation/', views.reservation, name="reservation"),
    path('menu/', views.menu, name="menu"),
    path('cart/', views.cart, name="cart"),
    path('gallery/', views.gallery, name="gallery"),
]

restaurant/restaurant/urls.py
from django.urls import path, include
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from indianexpress.views import home, signup, menu, reservation, cart,gallery

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('indianexpress.urls', namespace="indianexpress")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('shop/', include('shop.urls', namespace='shop')),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

restaurant/shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list,
         name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail,
         name='product_detail'),
]

restaurant/shop/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=200,
                            db_index=True)
    slug = models.SlugField(max_length=200,
                            unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category',
                       args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category,
                                 related_name='products',
                                 on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d',
                              blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail',
                       args=[self.id, self.slug])

restaurant/shop/views.py
from django.shortcuts import render, get_object_or_404

from cart.cart import Cart
from .models import Category, Product
from cart.forms import CartAddProductForm


def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request,
                  'shop/product/list.html',
                  {'category': category,
                   'categories': categories,
                   'products': products})


def product_detail(request, id, slug):
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)
    cart_product_form = CartAddProductForm()
    return render(request,
                  'shop/product/detail.html',
                  {'product': product,
                   'cart_product_form': cart_product_form})

restaurant/shop/templates/shop/base.html
{# HTML5 declaration #}
<!DOCTYPE html>
{% load static %}
<html lang="en">
    {# Make modifiable head elements #}
   <head>

    <title>Indian Xpress</title>
       <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <link href="{% static "css/base.css" %}" rel="stylesheet" >
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>


    <style>

        /* Remove the navbar's default margin-bottom and rounded borders */

        .navbar {
            margin-bottom: 0;
            border-radius: 0;
        }

        /* Set height of the grid so .sidenav can be 100% (adjust as needed) */
        .row.content {
            height: 450px
        }

        .navbar-brand {
            font-size: xx-large !important;
        }

        /* Set black background color, white text and some padding */
        footer {
            background-color: black;
            color: white;
            padding: 15px;
        }
        .product-list {
            padding: 25px 50px 75px 100px;
            background-color: lightblue;
        }


    </style>

    </head>
    <body id="app-layout">
        <nav class="navbar navbar-inverse">
            <div class="container-fluid">
            <div class="navbar-header">
                <!-- Collapsed Hamburger -->
                <button type="button" class="navbar-toggle" data-toggle="collapse"
                        data-target="#myNavbar">
                    <span class="sr-only">Toggle Navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!-- Branding Image -->
                <a class="navbar-brand" href="/">IndianXpress</a>
            </div>
            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'indianexpress:home' %}">About</a></li>

                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Menu
                        <span class="caret"></span>
                        </a>
                            <ul class="dropdown-menu">
                            <li {% if not category %}class="selected"{% endif %}>
                                <a href="{% url "shop:product_list" %}">All</a>
                            </li>
                              {% for c in categories %}
                                <li {% if category.slug == c.slug %}class="selected"{% endif %}>
                                  <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
                                </li>
                              {% endfor %}
                            </ul>

                    </li>
                    </li>
                    <li><a href="{% url 'indianexpress:gallery' %}">Gallery</a></li>
                    <li><a href="{% url 'indianexpress:cart' %}">Cart</a></li>
                    <li><a href="{% url 'indianexpress:reservation' %}">Reservation</a></li>



                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="{% url 'logout' %}"><i class="fa fa-btn fa-sign-out"></i>Logout</a></li>
                            </ul>
                        </li>
                    {% else %}
                        <li><a href="{% url 'login' %}">Login</a></li>

                    {% endif %}
                </ul>
            </div>
            </div>
        </nav>




  <div id="subheader">
    <div class="cart">
      {% with total_items=cart|length %}
          {% if cart|length > 0 %}
            Your cart: 
            <a href="{% url "cart:cart_detail" %}">
              {{ total_items }} item{{ total_items|pluralize }},
              ${{ cart.get_total_price }}
            </a>
          {% else %}
            Your cart is empty.
          {% endif %}
        {% endwith %}
    </div>
  </div>

{#  <div class="product-detail">#}
{#    <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">#}
{#    <h1>{{ product.name }}</h1>#}
{#    <h2><a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a></h2>#}
{#    <p class="price">${{ product.price }}</p>#}
{#    <form action="{% url "cart:cart_add" product.id %}" method="post">#}
{#      {{ cart_product_form }}#}
{#      {% csrf_token %}#}
{#      <input type="submit" value="Add to cart">#}
{#    </form>#}
{#    {{ product.description|linebreaks }}#}
{#  </div>#}

    {% block content %}
    {% endblock %}
  </div>
</body>
</html>